program testsort
    use thrust

    real, allocatable :: cpuData(:)
    real, allocatable, device :: gpuData(:)
    integer:: N=10

    allocate(cpuData(N))
    allocate(gpuData(N))

    do i=1,N
    cpuData(i)=random(i)
    end do

    cpuData(5)=100.

    print *,"Before sorting", cpuData
    gpuData=cpuData

    call thrustsort(gpuData,size(gpuData))
    cpuData=gpuData
    print *,"After sorting", cpuData

end program